name: docs

on:
  workflow_run:
    workflows: ["tests"]
    branches:
      - main
      - test-ci
    types:
      - completed

jobs:
  pages:
    runs-on: ubuntu-latest
    steps:

      - name: checkout
        uses: actions/checkout@v3

      - name: pysetup
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: install
        run: |
          sudo apt update

          # For Fortran extensions
          sudo apt install -y --no-install-recommends \
            python3-dev gfortran liblapack-dev

          # sphinx related
          pip install -r requirements_doc.txt

          # sphinx-autodoc needs target package to be installed
          pip install -e .

      - name: build
        run: |
          cd doc
          sh generate-doc.sh

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # base dir is checkout: /path/to/psweep
          publish_dir: doc/build/html
