name: tests

on:
  push:
    branches:
      - master
      - test-ci

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          ##- "3.8"
          ##- "3.9"
          ##- "3.10"
          - "3.11"

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: pysetup
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: install
        run: |
          sudo apt update

          # For Fortran extensions
          sudo apt install -y --no-install-recommends \
            python3-dev gfortran liblapack-dev

          sudo apt install -y --no-install-recommends \
            lammps quantum-espresso

          pip install -e .
          pip install -r requirements_optional.txt
          pip install -r requirements_test.txt

      - name: run tests
        run: |
          cd test
          ./runtests.sh --nobuild -n8

